config/routes.rb
Rails.application.routes.draw do
  root :to => "stores#index"
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'  
  

  resources :stores do
    resources :products do
      collection do
        get 'search'
      end  
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :name, type: String
  field :price, type: Float
  field :installments, type: Integer
  field :image, type: String
  field :url, type: String
  belongs_to :store
  mount_uploader :image, ImageUploader

  searchkick match: :word_start, searchable: [:name]

  def search_data
    { 
      name: name,
      store_id: store.id.to_s
    }
  end
end

app/models/store.rb
class Store
  include Mongoid::Document
  field :name, type: String
  field :website, type: String
  field :logo, type: String
  field :email, type: String
  has_many :products, dependent: :destroy
  mount_uploader :logo, LogoUploader
  
  searchkick
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  
  def search 
    if params[:search].present?    
      @products = Product.search params[:search], where: {store_id: params[:store_id]}      
    else            
      @products = Product.where(store_id: params[:store_id])
      # redirect_to(root_path) and return        
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :installments, :image, :url, :store_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]


  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end


  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :website, :logo, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :installments %>
    <%= form.number_field :installments %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.text_field :store_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<p>
  <div class="col-3 product">    
    <%= link_to(product.url) do %>
    <%= image_tag(product.image_url(:thumb).to_s) %>         
    <h5><%= product.name %></h5>    
    <a class="price"> R$ <%= product.price %></a>
    <a class="installments"> <%= product.installments %>x  R$<%= product.price / product.installments %> </a>  
    <% end %>
  </div>
</p>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Installments</th>
      <th>Image</th>
      <th>Url</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.installments %></td>
        <td><%= product.image %></td>
        <td><%= product.url %></td>
        <td><%= product.store_id %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
  <div class="container">
    <section class="section products">  
        <div class="row align-items-start products-list" >
          <%= render @products %>   
        </div>  
    </section>
  </div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<p>

  <%= image_tag(@product.image_url(:thumb).to_s) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Installments:</strong>
  <%= @product.installments %>
</p>

<p>
  <strong>Url:</strong>
  <%= @product.url %>
</p>

<p>
  <strong>Store:</strong>
  <%= @product.store_id %>
</p>

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

 

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

    <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light  bg-light main-nav">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-1">
            <ul class="nav navbar-nav w-100">
                <li class="nav-item active">
                    <a class="nav-link" href="#">HOMEM</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">MULHER</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">KIDS</a>
                </li>
            </ul>
        </div>
        <div class="order-first order-md-0 d-flex justify-content-center">
            <a class="navbar-brand mx-0" href="#"><%= image_tag(@store.logo_url(:thumb).to_s) %></a>
        </div>
        <div class="collapse navbar-collapse flex-1">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">CARRINHO</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<% controller.redirect_to('/admin') %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<%= render partial: "navbar" %>

<div class="container">
  <div class="row justify-content-end">
    <div class="col-4">
    <p id="notice"><%= notice %></p>  
      <%= form_tag search_store_products_path([@store.id]), method: :get, class: "form-inline my-2 my-lg-0", id:"search-form", role: "search" do %>
        <p>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder:"Ex: Relógio" %>
            <%= submit_tag "Buscar", name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
        </p>
      <% end %>
   </div>
 </div>

  <section class="section products">  
      <div class="row align-items-start products-list" >
        <%= render @store.products %>   
      </div>  
  </section>
</div>